Repository heidelbergcement/hcrystalball, pull requests merged in 2020-07, with the labels that each got.

#13 Optional dependencies import
  .github/workflows/ci-conda.yml
  README.md
  docs/contribution.rst
  docs/examples/01_quickstart.ipynb
  docs/examples/02_tutorial.ipynb
  docs/examples/tutorial/wrappers/02_ar_modelling_in_sklearn.ipynb
  docs/examples/tutorial/wrappers/05_model_selection.ipynb
  docs/index.rst
  docs/model_selection.rst
  src/hcrystalball/wrappers/__init__.py
Labels: bug

#14 Add conda installation instructions
  README.md
  docs/install.rst
  environment.yml
Labels: documentation

#16 Fix pytest coverage in CI for Windows
  .github/workflows/ci-conda.yml
Labels: bug

#17 Readme update with forecast picture
  README.md
  docs/_static/forecast.png
  docs/examples/01_quickstart.ipynb
Labels: documentation

#18 Add prefect to env.yml, add tests
  environment.yml
  src/hcrystalball/model_selection/_configuration.py
  tests/unit/model_selection/test_configuration.py
  tests/unit/preprocessing/test_endog_transformer.py
Labels: enhancement

#19 Return plots from model_selector plotting methods, update forecast.png
  docs/_static/forecast.png
  src/hcrystalball/model_selection/_model_selector.py
Labels: documentation, enhancement

#20 Fixes dependencies import, adds matplotlib as core dependency
  README.md
  docs/contribution.rst
  docs/examples/01_quickstart.ipynb
  docs/examples/02_tutorial.ipynb
  docs/examples/tutorial/model_selection/01_model_selector_basic.ipynb
  docs/examples/tutorial/model_selection/02_model_selector_result_basic.ipynb
  docs/examples/tutorial/model_selection/03_model_selector_advanced.ipynb
  docs/examples/tutorial/wrappers/01_wrappers_intro.ipynb
  docs/install.rst
  setup.cfg
  src/hcrystalball/model_selection/_configuration.py
  src/hcrystalball/model_selection/_model_selector.py
  src/hcrystalball/wrappers/__init__.py
  tests/unit/model_selection/test_configuration.py
  tests/unit/model_selection/test_model_selector.py
  tests/unit/model_selection/test_prefect_executors.py
Labels: bug, documentation

#23 Update binder env cache trigger
  .github/workflows/create_binder_env.yml
  docs/examples/01_quickstart.ipynb
  docs/examples/02_tutorial.ipynb
Labels: documentation, enhancement

#24 Create binder docker on push
  .github/workflows/create_binder_env.yml
Labels: documentation, enhancement

#25 Format docs
  .github/workflows/create_binder_env.yml
  README.md
  dev/run_nb.py
  docs/contribution.rst
  docs/data_format.rst
  docs/index.rst
  docs/model_selection.rst
  setup.cfg
  src/hcrystalball/ensemble/_stacking_ensemble.py
  src/hcrystalball/model_selection/_configuration.py
  src/hcrystalball/model_selection/_large_scale_cross_validation.py
  src/hcrystalball/model_selection/_model_selector_result.py
  src/hcrystalball/utils.py
  src/hcrystalball/wrappers/_sarimax.py
  src/hcrystalball/wrappers/_smoothing.py
  tests/conftest.py
  tests/integration/test_data_unchanged.py
  tests/integration/test_models_integration.py
  tests/unit/feature_extraction/test_holiday_transformer.py
  tests/unit/model_selection/test_data_preparation.py
  tests/unit/model_selection/test_model_selection_utils.py
  tests/unit/model_selection/test_time_splitter.py
  tests/unit/test_utils.py
  tests/unit/wrappers/test_prophet_wrapper.py
  tests/unit/wrappers/test_sarimax_wrapper.py
Labels: documentation, good first issue

#26 update visual side
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/precache_binder.yml
  README.md
Labels: documentation

#29 Update precache_binder.yml
  .github/workflows/precache_binder.yml
Labels: bug

#34 Improve and test optional imports
  dev/wrapper_after.drawio
  dev/wrapper_before.drawio
  docs/examples/01_quickstart.ipynb
  docs/examples/tutorial/model_selection/01_model_selector_basic.ipynb
  docs/examples/tutorial/model_selection/02_model_selector_result_basic.ipynb
  docs/examples/tutorial/model_selection/03_model_selector_advanced.ipynb
  environment.yml
  src/hcrystalball/utils.py
  src/hcrystalball/wrappers/__init__.py
  tests/integration/test_data_unchanged.py
  tests/unit/model_selection/test_prefect_executors.py
  tests/unit/test_utils.py
Labels: enhancement
